import html2canvas from 'html2canvas';

export const exportRoastImage = async (elementId: string, action: 'download' | 'share'): Promise<void> => {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element with id ${elementId} not found`);
    return;
  }

  try {
    // Generate Canvas
    const canvas = await html2canvas(element, {
      scale: 2, // High resolution
      useCORS: true,
      backgroundColor: null, // Transparent if needed, though usually cards have bg
      logging: false,
    });

    // Convert to Blob
    const blob = await new Promise<Blob | null>((resolve) => {
      canvas.toBlob((b) => resolve(b), 'image/png', 1.0);
    });

    if (!blob) throw new Error("Failed to create image blob");

    const fileName = `m-star-roast-${Date.now()}.png`;

    if (action === 'share') {
      // Check if Web Share API Level 2 (File Sharing) is supported
      if (navigator.share && navigator.canShare && navigator.canShare({ files: [new File([blob], fileName, { type: blob.type })] })) {
        try {
          const file = new File([blob], fileName, { type: blob.type });
          await navigator.share({
            title: 'M-Star AI Roast',
            text: 'Check out this roast generated by M-Star AI Studio! 🔥',
            files: [file],
          });
        } catch (shareError) {
          console.warn('Share failed or cancelled', shareError);
          // Optional: Fallback to download if share fails hard
          downloadImage(blob, fileName);
        }
      } else {
        // Fallback for browsers/webviews that don't support file sharing
        alert("Sharing not supported on this browser. Downloading image instead.");
        downloadImage(blob, fileName);
      }
    } else {
      // Download Action
      downloadImage(blob, fileName);
    }

  } catch (error) {
    console.error("Image Export Error:", error);
    alert("Could not generate image. Please try again.");
  }
};

const downloadImage = (blob: Blob, fileName: string) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};